Burn - Simple Calorie Counter
espruino/BangleApps pull request #3445
Opened 2024-06-07 21:40 UTC by slynchDev

Calorie count persists to kcal.txt and clears at midnight. Increment (step) value can be changed as needed

2024-06-09 14:16 UTC, thyttan requested changes

2024-06-09 14:16 UTC, thyttan commented on apps/burn/burn.js
> +  y = 100;
Lint warning: `'y' is assigned a value but never used`

So seems like you could just remove it?

2024-06-09 14:16 UTC, thyttan commented on apps/burn/burn.js
> +  x = 25;
And likewise here: `'x' is assigned a value but never used`

2024-06-09 14:57 UTC, thyttan commented on apps/burn/.prettierignore
I think this is just for formatting locally on your machine? We'll probably want to not have that file on the repo. What do you think @bobrippling @halemmerich ?

2024-06-09 15:11 UTC, thyttan commented
Thanks! I left some comments. 

If you want to let the calculation run in the background you could implement it in a `burn.boot.js` file or as a widget. But no need to do that in this PR - just a feature suggestion for the future.

Also I'd prefer if filenames were renamed from 
`burn.js`, `burn_icon.png` and `burn-icon.js`
 to simply 
`app.js`, `app.png` and `app-icon.js` as is common in the repo.

2024-06-09 20:24 UTC, slynchDev commented
thank you, I'll make your suggested changes

2024-06-09 20:24 UTC, closed without merging

2024-06-09 20:41 UTC, thyttan commented
OK - looking forward to see it when your ready again! 🙂

2024-06-16 15:18 UTC, bobrippling commented on apps/burn/.prettierignore
Yeah I agree, thanks for taking this :)